In [2]:
import math as mt
import numpy as np

In [145]:
def TriangularSuperior(M,v):
    A = np.copy(M)
    b = np.copy(v)
    for i in range(4):
        b[i] = b[i]/A[i][i]
        A[i] = A[i]/A[i][i]
        for j in range(i+1,4):
            b[j] = b[j] - (A[j][i])*b[i]
            A[j] = A[j] - (A[j][i])*A[i]
    return A,b

In [174]:
x = np.zeros(4)
A = [[2,1,4,1],
     [3,4,-1,-1],
     [1,-4,1,3],
     [2,-2,1,3]]
A = np.array(A,float)
b = np.array([-4,3,9,7],float)

A1,b1 = TriangularSuperior(A,b)
print(A1)
b1

[[ 1.          0.5         2.          0.5       ]
 [ 0.          1.         -2.8        -1.        ]
 [-0.         -0.          1.          0.14705882]
 [ 0.          0.          0.          1.        ]]


array([-2.        ,  3.6       , -2.        , -1.47826087])

In [169]:
x[3] = b1[3]
x[2] = b1[2] - x[3]*A1[2][3]
x[1] = b1[1] - x[2]*A1[1][2] - x[3]*A1[1][3]
x[0] = b1[0] - x[1]*A1[0][1] - x[2]*A1[0][2] - x[3]*A1[0][3]
x

array([ 3.73913043, -2.86956522, -1.7826087 , -1.47826087])

In [170]:
np.dot(A,x)

array([-4.,  3.,  9.,  7.])

In [179]:
x = np.zeros(4)

for i in range(3,-1,-1):
    s = 0
    for j in range(3,-1,-1):
        s = s + x[j]*A1[i][j]
    x[i] = b1[i] - s
x

array([ 3.73913043, -2.86956522, -1.7826087 , -1.47826087])

In [180]:
np.dot(A,x)

array([-4.,  3.,  9.,  7.])