<h1 align="center">Física Computacional.</h1>
<h1 align="center">Intersemestral 2025-4</h1>

<h2>Sergio A. Alcalá Corona </h2> 

---
### Rodrigo Vega Vilchis
---

<h1 align="center">Programación para la física computacional</h1> 

# 1.1. Fundamentos de programación

---

### Interprete de comandos de *Python* 
---

**Python** es un interprete de comandos que se ejecuta en una consola (terminal de linux, Windows, Jupyter, Colab o algun programa especializado). En este se escriben comandos como **entrada** y el interprete regresa una respuesta como **salida**.

Python puede guardar datos como texto o valores numéricos en variables, así como utilizar estructuras de control, lo que permite realizar instrucciones repetidamente o evaluar valores para poder tomar decisiones. De esta manera, se pueden escribir _**scripts**_ para  realizar cálculos de computo científico, ya que dispone de un extenso numero de bibliotecas (_libraries_) diseñadas para realizar fácilmente diferentes tareas.

Es un lenguaje de programación (interpretado), que por si fuera poco es orientado a objetos, ya que las bibliotecas y funciones que se pueden construir permiten programarse y usarse bajo este paradigma. A pesar de su gran **robustez** y versatilidad Python es un lenguaje muy fácil de  aprender y de usar. Por lo que es ideal para comenzar a programar y como una herramienta eficaz para acercarse por primera vez al computo científico.

### *Ipython* y celdas de Jupyter

**ipython** (*Interactive Python*) es un interprete de Python pero mucho mas robusto que el nativo (y es la base de los cuadernos de *Jupyter*), está diseñado para maximizar la productividad al utilizar Python. Aquí podemos encontrar ciertas facilidades, utilidades y comandos que no existen en otros interpretes de Python.

Por ejemplo una utilidad de gran ayuda es que se puede consultar la documentación (o sea, para qué sirve) de comandos, módulos y/o funciones de `python` usando `?` despues de la función.

In [ ]:
range?

O incluso, se puede consultar el `código fuente` de estas (cuando está disponible) usando `??` 

In [ ]:
range??

## BIBLIOTECAS

La gran versatilidad de python vine dada en gran parte por el conjunto de **bibliotecas** que este ya tiene incorporadas, así que hay que aprovechar lo que ya esta hecho! Por ejemplo:

* `python-numpy` **biblioteca de arreglos matemáticos**

* `python-scipy` **rutinas para uso científico**

* `python-matplotlib` **gráficas en 2 dimensiones**

* `python-pandas` **para manejo de grandes conjuntos de datos con DataFrames**

* `python-sklearn` **para Machine Learning**


<!-- * `python-visual` **animaciones en 3 dimensiones**


* `mayavi2` -->


## El ecosistema Científico de python
<p>
$\;$
<p>

<!-- ![ScyentificPythpn_Ecosystem.png](attachment:ScyentificPythpn_Ecosystem.png) -->
<div align="center">
    <img src="ScyentificPythpn_Ecosystem.png">
</div>

Estas serán las bibliotecas principales que estaremos usando durante el curso.

Para instalar **bibliotecas** en python podemos correr desde la Terminal (**bash** en linux, **cmd** en Windows o la terminal de **mac**) el siguiete comando

`python -m pip install` *`BIBLIOTECA`*

Python cuenta una biblioteca estándar amplia, lo cual siempre está disponible en cualquier instalación de Python.

La documentación para esta biblioteca está disponible en http://docs.python.org/library/

Sin embargo para poder hacer un uso mucho más amplio y poderoso de python se puede hacer uso del resto de las bibliotecas disponibles una vez que estén instaladas. Por ejemplo para llevar a cabo cálculos con funciones más avanzadas, es necesario **importar** la biblioteca estándar de matemáticas `math`.

Así ya instaladas se puede hacer uso de las bibliotecas **importándolas**, para que *python* sepa que las debe usar.

Para esto se debe dar una instrucción especial (*sentencia de importación*) para que python (ya sea en el *interprete de comandos*, `Ipython`, `Jupyter` bien en un *script*) pueda acceder a ellas.

Para poder usar una biblioteca (o parte de ella) simplemente se tiene que indicar que biblioteca estamos llamando e importar de ella lo que vamos a usar.

Por ejemplo:

In [ ]:
from fractions import Fraction

Aquí se está importando la función `Fraction` de la biblioteca `fractions` (que está en la sección 9 de la biblioteca estándar). O bien:

In [ ]:
from math import *

Aquí se está importando **todas** las funciones de las bibliotecas `math`.

**NOTA**: Cuando llamamos una función de una biblioteca que no está instalada o no se ha importado python nos reportará un error.

También se puede importar parcialmente una biblioteca. Es decir, sólo la sub-biblioteca que nos interese, para ser el código más eficiente. Por ejemplo:

In [ ]:
from scipy import stats

Y también se puede importar la biblioteca bajo un *alias* que la contenga, por ejemplo:

In [ ]:
import pandas as pd

Como ya se menciono *Python* es tan poderoso pues es lenguaje **orientado a objetos**.

Cada **"cosa"** en *Python* es un **objeto**, que tiene propiedades y operaciones disponibles (**métodos**). 

Por ejemplo, `Fraction` es un tipo de objeto (**clase**); sus operaciones están disponibles en *Ipython* a través de `Fraction.<TAB>`. 

Las que empiezan con `__` son internos y deberan de ignorarse por el momento; las demás son accesibles al usuario.

In [ ]:
Fraction.

In [ ]:
pd.

#### Manejo de Información

Python (ya sea mediante el interprete de comandos o bien mediante el entorno *Ipython* o *Jupyter*) nos permite resolver problemas y realizar operaciones matemáticas de una manera  interactiva, en la que se ejecutan comandos (entrada) y *python* a su vez da una respuesta (salida) en el mismo momento.

---
## 1.1.1 Aritmética, variables y tipos de datos
---
$\;$
### Aritmética 

---
*python* se puede usar como si fuera una **calculadora** muy potente.

De esta manera podemos realizar funciones aritméticas usando los operadores que ya se han mencionado y que son estándares en casi todos los lenguajes de programación Suma (`+`), Resta (`-`), Producto (`*`), División (`/`).

In [1]:
3 + 2 + 200000

200005

In [2]:
3 * (-7.1 + 10**3)

2978.7

In [3]:
2**10

1024

Aquí `**` indica una potencia, y los paréntesis alteran la prioridad en las operaciones.


Los números sin punto decimal se consideran enteros, y los con punto decimal flotantes (de doble precisión).

Los enteros pueden ser arbitrariamente grandes:

In [7]:
a = 2 ** (2 ** (2 ** 2)) 

$a = 2^{2^{2^2}}$

$a = 2^{2^{4}}$

$a = 2^{16}$

In [12]:
a = 2 ** 2 ** 2 ** 2
a = a ** 2 ** 2

Corre la siguiente celda para ver que número es `a`

In [13]:
print(a)

18446744073709551616


In [15]:
b=0.55

In [16]:
a+b

1.8446744073709552e+19

In [14]:
print(a**2)

340282366920938463463374607431768211456


Python también cuenta con números complejos, utilizando la notación `1j` para la raiz de `−1`:

In [17]:
1 + 3j

(1+3j)

In [18]:
1j * 1j

(-1+0j)

In [23]:
j # sólito, da un error, debe de ser 1j

NameError: name 'j' is not defined

In [26]:
a = 1j

In [27]:
a**2

(-1+0j)

In [28]:
int(a**2)

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'complex'

También existen operaciones para manejar la parte entera ( `//`) y el residuo de una divisón ( `operacion modulo` `%`):

In [34]:
a = 25.453

In [36]:
13//5  #parte entera


2

In [37]:
13%5  # modulo

3

`#` indica un comentario (no se lee, por lo que no cuenta) que se extiende hasta el final de la línea.

In [ ]:
# Esto es un "comentario" (no se lee, por lo que no cuenta) que se extiende hasta el final de la línea.

In [38]:
2+3j/5-7j

(2-6.4j)

*Python* también incluye **en la biblioteca `math`** valores para números irracionales muy usados como $e$ y $\pi$:

In [45]:
import math as mt

In [46]:
mt.pi

3.141592653589793

In [47]:
int(mt.pi)

3

In [49]:
round(5.49)

5

In [50]:
round(5.5)

6

In [51]:
mt.e

2.718281828459045

In [54]:
print(mt.pi**2)

9.869604401089358


Así como funciones muy utiles como el *logaritmo natural* $\ln(x)$ o la exponencial $e^x$

In [ ]:
from math import log
from math import exp

In [56]:
mt.log

<function math.log>

In [59]:
mt.floor(9.88)

9

In [64]:
mt.ceil(9.88)

10

Asimismo, podemos importar una función desde un módulo particular de una biblioteca, de la siguiente manera:

In [71]:
from numpy.linalg import inv

$\;$
### Variables y tipos de datos

---

Para llevar a cabo cálculos, necesitamos **variables**.
Las variables se declaran sin **necesidad de indicar su tipo de dato** (entero, flotante, etc.):

In [57]:
a = 3   # entero
b = 17.5   # flotante
c = 1 + 3j  # complejo

print (a + b / c)

(4.75-5.25j)


Python reconoce de manera automática el tipo de la variable según su forma. 

La función **`print()`** imprime el argumento (valor interior) de la variable.

Recordemos que el símbolo `=` **no es equivalente al símbolo igual en matemáticas**, en programación este símbolo significa **asignación** (es decir, guardar un valor en una variable) y asimismo sirve para reasignarle un valor a la misma. 

En python, al reasignar una variable, se pierde la información de su valor interior, incluyendo el tipo:

In [65]:
a = 3
print(a)

a = -5.5
print(a)

3
-5.5


Por lo que hay que tener cuidado al usar el el símbolo `=` para no perder información.

#### Conversión entre tipos de datos.

Aunque no haya que declararlos al definir variables, hay distintos tipos de números en Python, principalmente enteros (**`int`**) y flotantes (**`float`**).

Para convertir entre diferentes tipos, incluyendo cadenas, podemos utilizar:

In [66]:
a = float(3)
print(a)

pi_short = float('3.1416')
print(pi_short)

Mypi = int(pi_short)
print(Mypi)

b = int(17.)
print(b)

edad = int("19")
print(edad)

year = str(1998)
print(year)

3.0
3.1416
3
17
19
1998


Las _"palabras"_ en Python son `cadenas` de caracteres entre apóstrofes o comillas.

In [67]:
"hola"
'mi edad es: '

'mi edad es: '

se pueden concaternar cadenas usado el simbolo `+`

In [68]:
cadena = "hola " + 'mi edad es: '

In [69]:
cadena

'hola mi edad es: '

In [70]:
len(cadena)

17

#### Aritmética con precisión arbitraria.

A veces, es necesario poder llevar a cabo operaciones aritméticas con números flotantes (*reales*) con precisión superior a los **16 dígitos** que provee el **float** (número de **doble precisión**) de Python. Para hacerlo, existen varios proyectos que proveen bibliotecas con este fin.

Una opción, la biblioteca **`mpmath`**, que está escrita completamente en Python. En principio eso lo hace más lento, pero más fácil de entender y modificar el código.

Para cargar la biblioteca, hacemos:

In [ ]:
from mpmath import *

---
## 1.1.2. Estructuras de datos, estructuras de control y funciones
$\;$
### Listas y arreglos numpy (vectores y matrices).

---

En Python hay 3 tipos diferentes de arreglos. Las **listas**, las **n-adas** (o tuples) y los **arreglos numpy**, estos últimos son mas robustos y con ellos se puede representar vectores e incluso matrices.

#### Listas

La estructura de datos principal en Python es la lista. Consiste literalmente en una lista ordenada de cosas, y
reemplaza a los arreglos en otros lenguajes. La diferencia es que las listas en *Python* son automáticamente de longitud variable, y pueden contener objetos de cualquier tipo.

Una lista se define entre corchetes (`[y]`):

In [73]:
l = [3, 4, 6]

In [74]:
l

[3, 4, 6]

In [75]:
r = [ 1, 1, 2, 3, 5, 8, 13, 21 ]
print(r)

[1, 1, 2, 3, 5, 8, 13, 21]


In [81]:
len(r)

8

In [85]:
r[6]+17

30

Puede contener cualquier cosa, ¡incluyendo a otras listas!:



In [89]:
l2 = [3.5, -1, "hola", [1.0, [3, 17]]]
l2[3][1][0]

3

Los elementos de la lista se pueden extraer y cambiar usando la notación `lista[i]`, donde `i` indica el número del elemento, empezando desde `0`:



In [90]:
l3 = [1, 2, 3]
print(l3[0],l3[1])

1 2


Y así también se pueden reasignar sus valores: 

In [91]:
l[0] = 5
l

[5, 4, 6]

In [92]:
r = [ 1.0,1.5, -2.2 ]
r[1] = 3.5

print(r)

[1.0, 3.5, -2.2]


Se puede hacer una lista a partir de diferentes variables:

In [93]:
x = 1.0
y = 1.5
z = -2.2
r = [ x, y, z ]

print(r)

[1.0, 1.5, -2.2]


O bien, definir una lista a partir de operaciones con variables:

In [95]:
r = [ 2*x, x+y, z/mt.sqrt(x**2+y**2) ]
print(r)

[2.0, 2.5, -1.2203404316955042]


In [97]:
#from math import sqrt

r = [ 1.0, 1.5, -2.2 ]
norma = mt.sqrt(r[0]**2 + r[1]**2 + r[2]**2)
print(norma)

2.8442925306655784


Se pueden sumar los elementos de la lista de la siguiente manera:

In [98]:
r = [ 1.0, 1.5, -2.2 ]
total = sum(r)
print(total)

0.2999999999999998


In [104]:
round(total,10)

0.3

In [105]:
total

0.2999999999999998

o calcular el promedio de las mismas

In [106]:
r = [ 1.0, 1.5, -2.2 ]
promedio = sum(r)/len(r)
print(promedio)

0.09999999999999994


#### La función `map`


Una función especialmente útil para las listas es `map`, que permite aplicar funciones ordinarias, como `log`  o `sqrt`, a todos los elementos de una lista a la vez. Así, `map(log,r)` toma el logaritmo natural de cada elemento de la lista `r`:

In [108]:
from math import log

r = [ 1.0, 1.5, 2.2 ]
logr = list(map(log,r))

print(logr)

[0.0, 0.4054651081081644, 0.7884573603642703]


In [109]:
pow?

Signature: pow(base, exp, mod=None)
Docstring:
Equivalent to base**exp with 2 arguments or base**exp % mod with 3 arguments

Some types, such as ints, are able to use a more efficient algorithm when
invoked using the three argument form.
Type:      builtin_function_or_method

In [112]:
r = [ 1.0, 1.5, 2.2 ]
list(map(log,r))

[0.0, 0.4054651081081644, 0.7884573603642703]

In [115]:
for i in (map(log,r)):
    print(i)

0.0
0.4054651081081644
0.7884573603642703


#### Rebanadas (“*slices*”) 

También se pueden manipular rebanadas (“*slices*”) de la lista con la notación `l[i:j]` donde `i` indica el elemento a partir del cual se va a tomar la rebanada y `j` indica hasta que elemento se va a tomar la rebanada **sin incluirlo**.

In [116]:
ls = [1, 2, 3, 6, 7]

In [117]:
ls[1:3]

[2, 3]

In [118]:
ls[:3]

[1, 2, 3]

In [119]:
ls[3:]

[6, 7]

In [120]:
ls[4]

7

In [121]:
ls[5]

IndexError: list index out of range

In [123]:
r = [ 1, 3, 5, 7, 9, 11, 13, 15 ]
s = r[2: 5]

print(s)

[5, 7, 9]


In [124]:
len(r)

8

In [125]:
r[0:len(r)]

[1, 3, 5, 7, 9, 11, 13, 15]

In [126]:
r[2:]

[5, 7, 9, 11, 13, 15]

In [127]:
r [:5]

[1, 3, 5, 7, 9]

¿qué pasa si no ponemos nada?

In [128]:
r [:]

[1, 3, 5, 7, 9, 11, 13, 15]

#### Función `len()`

La longitud de una lista se puede encontrar con `len(`*`lista`*`)`:

In [130]:
len(ls)

5

#### Funciones `append()` y `pop()`



Se pueden agregar elementos a la lista con `append()`:

In [157]:
l = [] # asi creamos una lista vacíal

In [167]:
l.append(17)
l.append(3)

In [182]:
l

[]

In [180]:
l.pop()

IndexError: pop from empty list

In [183]:
print (l, len(l))

[] 0


In [185]:
r = [ 1.0, 1.5, -2.2 ]
print(r)

[1.0, 1.5, -2.2]


In [186]:
r.append(6.1)

In [187]:
r = [ 1.0, 1.5, -2.2]

x = 0.8
r.append(2*x+1)

print(r)

[1.0, 1.5, -2.2, 2.6]


In [188]:
r = []  # lista vacía

r.append(1.0)
r.append(1.5)
r.append(-2.2)
print(r)


[1.0, 1.5, -2.2]


y de igual manera se pueden remover elementos de la lista con `pop()`:

In [201]:
r = [ 1.0, 1.5, -2.2, 2.6 ]

r.pop()
print(r)

[1.0, 1.5, -2.2]


**Nota**: `append()` y `pop()` manejan la lista como una `pila` (_stack_), esto es: "lo primero que entra es lo ultimo que sale y viceversa.

Como siempre, las otras operaciones que se pueden llevar a cabo con la lista se pueden averiguar en ipython con:
`l.<TABULADOR>`

In [230]:
r = [ 1.0, 1.5, -2.2, 2.6 ]

r.count(1.5)

1

In [231]:
r2 = r
r2

[1.0, 1.5, -2.2, 2.6]

In [239]:
r.pop()

-2.2

In [240]:
r

[1.0, 1.5]

In [241]:
r2

[1.0, 1.5]

#### La función *range()*

Para averiguar que es lo que hace una función, se puede investigar de manera interactiva:

In [242]:
range?

Init signature: range(self, /, *args, **kwargs)
Docstring:     
range(stop) -> range object
range(start, stop[, step]) -> range object

Return an object that produces a sequence of integers from start (inclusive)
to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
These are exactly the valid indices for a list of 4 elements.
When step is given, it specifies the increment (or decrement).
Type:           type
Subclasses:     

`range(N)` en `python 2.x` devuelve una lista que contiene una progresión aritmética de enteros. Sin embargo en `python 3.x`,`range` es una función que nos devuelve un rango de números naturales a los cuales podemos acceder por medio de un iterador.

In [243]:
range(10)

range(0, 10)

Para obtener una _lista_ con los diez primeros números podemos utilizar un `for` (lo explicaremos más adelante) de la siguiente manera:

In [247]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [253]:
L = []
print(L)
for i in range(0,20,2):
    L.append(i)
    print(L)

[]
[0]
[0, 2]
[0, 2, 4]
[0, 2, 4, 6]
[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8, 10]
[0, 2, 4, 6, 8, 10, 12]
[0, 2, 4, 6, 8, 10, 12, 14]
[0, 2, 4, 6, 8, 10, 12, 14, 16]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [254]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Nótese que la lista comienza en 0 (cero) y que se omite el elemento final, por ejemplo para obtner una lista de cuatro elementos que llegue hasta el 3 se tiene:

In [255]:
[i for i in range(4)]

[0, 1, 2, 3]

También se le puede indicar en donde inicia y donde termina la lista:

In [256]:
[i for i in range(3,10)]

[3, 4, 5, 6, 7, 8, 9]

O bien también se le puede indicar un paso de incremento:

In [257]:
[i for i in range(3,17,2)]

[3, 5, 7, 9, 11, 13, 15]

In [258]:
[i for i in range(3,17,3)]

[3, 6, 9, 12, 15]

In [259]:
[i for i in range(3,17,5)]

[3, 8, 13]

Sobra decir que estas lista generadas por ´range´ las podemos almacenar en una variable.

In [260]:
x = [i for i in range(3,17,5)]

In [261]:
print(x)

[3, 8, 13]


También nótese que `range()` no acepta argumentos de punto flotante.

In [ ]:
[i for i in range(3.,10.)]

### Arreglos numpy (vectores).

Por lo general las listas y *tuples* se utilizan para guardar y manipular datos. Sin embargo, las listas no se comportan como vectores, y menos como matrices (al sumarlos no se comportan de la manera adecuada, etc.). El propósito de la biblioteca numpy es justamente el de proporcionar objetos que representan a vectores y matrices matemáticos, con todas las bondades que traen consigo este tipo de objetos.

La biblioteca se carga con:

In [1]:
from numpy import *

Y provee muchas funciones para trabajar con vectores y matrices.


Los vectores se llaman (aunque es un poco confuso) **arrays**, (arreglos) y se pueden crear de distintas maneras. Son como listas, pero con propiedades y **métodos** adicionales para funcionar como objetos matemáticos. La manera más general de crear un vector es justamente convirtiendolo desde una lista de números:

In [13]:
#from numpy import *

import numpy as np
a = array( [1, 2, -1, 100] )

In [3]:
a

array([  1,   2,  -1, 100])

In [7]:
a = array([1.0,1.5,-2.2] ,float)

In [8]:
a

array([ 1. ,  1.5, -2.2])

In [6]:
a**2

array([1.  , 2.25, 4.84])

In [14]:
v2 = np.array([1,2,3])
v2

array([1, 2, 3])

In [9]:
r = [ 1.0, 1.5, -2.2 ]
a = array(r,float)

In [16]:
a = np.array([1,2,3])
b = np.array([3,4,5])

a*b

array([ 3,  8, 15])

In [17]:
np.dot(a,b)

26

In [18]:
np.cross(a,b)

array([-2,  4, -2])

In [19]:
mt.exp(a)

NameError: name 'mt' is not defined

In [20]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

Aqui también se pueden hacer rebandas (*"slices"*)

In [24]:
a = np.array([2,4,6,8,10,12,14,16] ,int)

b = a[3 :6]
print(b)

[ 8 10 12]


In [25]:
print(a[3:])
print(a[:6])


[ 8 10 12 14 16]
[ 2  4  6  8 10 12]


In [ ]:
a [:]

Un vector de este tipo puede contener sólo un tipo de objetos, a diferencia de una lista normal de *Python*. Si todos los números en la lista son enteros, entonces el tipo del arreglo también lo es, como se puede comprobar con

In [28]:
a.dtype

dtype('int64')

In [27]:
type(a)

numpy.ndarray

Es común querer crear vectores de cierto tamaño con todas las entradas en ceros. Esto se puede hacer con la biblioteca `zeros` de `numpy`:

In [29]:
#from numpy import zeros

b = zeros(10)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [30]:
a = zeros(4,int)
print(a)

[0 0 0 0]


In [31]:
a = zeros(50, complex)
print(a)

[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]


o bien, todos unos:

In [32]:
b = ones(10)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Si se quiere crear un **arreglo "vacio"**, directamente (es decir, sin crear primero la lista vacia), se puede hacer con la biblioteca `empty` de `numpy`:

In [33]:
from numpy import empty
a = empty(4,float)

In [34]:
a

array([0., 0., 0., 0.])

También hay distintas maneras de crear vectores que consisten en rangos ordenados, por ejemplo **`arange`**, que funciona como `range`, con un punto inicial, un punto final, y un paso:

In [41]:
for i in range(0.5,2.1,0.1):
    print(i)

TypeError: 'float' object cannot be interpreted as an integer

In [40]:
for i in np.arange(0.5,2.1,0.1):
    print(i)

0.5
0.6
0.7
0.7999999999999999
0.8999999999999999
0.9999999999999999
1.0999999999999999
1.1999999999999997
1.2999999999999998
1.4
1.4999999999999998
1.5999999999999996
1.6999999999999997
1.7999999999999998
1.8999999999999997
1.9999999999999996


In [53]:
a = np.arange(0., 10., 1)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

y **`linspace`**, donde se especifica puntos iniciales y finales y un número de entradas:

In [41]:
l = np.linspace(0., 10., 99)
l

array([ 0.        ,  0.10204082,  0.20408163,  0.30612245,  0.40816327,
        0.51020408,  0.6122449 ,  0.71428571,  0.81632653,  0.91836735,
        1.02040816,  1.12244898,  1.2244898 ,  1.32653061,  1.42857143,
        1.53061224,  1.63265306,  1.73469388,  1.83673469,  1.93877551,
        2.04081633,  2.14285714,  2.24489796,  2.34693878,  2.44897959,
        2.55102041,  2.65306122,  2.75510204,  2.85714286,  2.95918367,
        3.06122449,  3.16326531,  3.26530612,  3.36734694,  3.46938776,
        3.57142857,  3.67346939,  3.7755102 ,  3.87755102,  3.97959184,
        4.08163265,  4.18367347,  4.28571429,  4.3877551 ,  4.48979592,
        4.59183673,  4.69387755,  4.79591837,  4.89795918,  5.        ,
        5.10204082,  5.20408163,  5.30612245,  5.40816327,  5.51020408,
        5.6122449 ,  5.71428571,  5.81632653,  5.91836735,  6.02040816,
        6.12244898,  6.2244898 ,  6.32653061,  6.42857143,  6.53061224,
        6.63265306,  6.73469388,  6.83673469,  6.93877551,  7.04

Una notación abreviada para construir vectores es `r_`, que se puede pensar como una abreviación de *“vector renglón”*:


In [ ]:
a = r_[1,2,10,-1.]
a

Este método se extiende para dar una manera rápida de construir rangos:

In [ ]:
r_[3:7]

In [ ]:
r_[3:7:0.5]

In [ ]:
r_[3:7:10j]

Este ultimo utiliza un *número complejo* simplemente como otra notación, y es el equivalente de `linspace(3,7,10)`.

#### Aritmetica con arreglos

Los vectores creados de esta manera se pueden sumar, restar etc., como si fueran vectores matemáticos. Todas las operaciones se llevan a cabo entrada por entrada:

In [4]:
v1 = array( [1., 4., 7. ])
v2 = array( [1., 2., -2. ])

print(v1, v2)

[1. 4. 7.] [ 1.  2. -2.]


In [55]:
v1+v2

array([2., 6., 5.])

In [56]:
v1-v2

array([0., 2., 9.])

In [57]:
v1*v2

array([  1.,   8., -14.])

In [58]:
v1/v2

array([ 1. ,  2. , -3.5])

In [59]:
v1**v2

array([ 1.        , 16.        ,  0.02040816])

In [60]:
a = array([1.0,1.5,-2.2,3.5] ,float)

In [61]:
a[0] = a[1] + 1
a

array([ 2.5,  1.5, -2.2,  3.5])

In [62]:
x = a[2]**2 - 2*a[3]/y
x

NameError: name 'y' is not defined

In [ ]:
from numpy import array

a = array([1,2,3,4] ,int)
b = 2*a
print(b)

In [ ]:
a = array([1,2,3,4] ,int)
b = array([2,4,6,8] ,int)
print(a+b)

In [ ]:
a = array([1,2,3,4] ,int)
print(a+1)

In [ ]:
a = array([1,2,3,4] ,int)
b = array([2,4,6,8] ,int)
print(a*b)

Las funciones más comunes entre vectores ya están definidas en **numpy**, entre las cuales se encuentran `dot(v1,v2)` para productos escalares de dos vectores de la misma longitud, y `cross(v1,v2)` para el producto cruz de dos vectores de longitud 3.

In [1]:
from numpy import array,dot, cross

a = array([1,2,3,4] ,int)
b = array([2,4,6,8] ,int)

print(dot(a,b))

60


In [5]:
print(v1)
print(v2)

[1. 4. 7.]
[ 1.  2. -2.]


In [6]:
dot(v1,v2)

-5.0

In [7]:
cross(v1,v2)

array([-22.,   9.,  -2.])

Además, cualquier función matemática como **`sin`** y **`exp`** se puede aplicar directamente a un vector, `y` regresará un vector compuesto por esta función aplicada a cada entrada del vector. Es más: al definir una función el usuario, esta función normalmente también se pueden aplicar directamente a un vector:


In [34]:
import math as mt

# Distribución gaussiana
def gauss(x):
    return 1./(mt.sqrt(2.)) * mt.exp(-x**2 / 2.)

In [35]:
gauss(-2)

0.09569649651041093

In [36]:
gauss(2)

0.09569649651041093

In [37]:
gauss(x)

TypeError: only length-1 arrays can be converted to Python scalars

In [38]:
import numpy as np

# Distribución gaussiana
def gauss(x):
    return 1./(np.sqrt(2.)) * np.exp(-x**2 / 2.)

In [39]:
x = np.arange(3,5,0.2)
x

array([3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [40]:
gauss(x)

array([7.85524678e-03, 4.22568631e-03, 2.18405161e-03, 1.08456793e-03,
       5.17462453e-04, 2.37207899e-04, 1.04473867e-04, 4.42093793e-05,
       1.79741923e-05, 7.02121983e-06])

In [42]:
gauss( r_[0:10] )

NameError: name 'r_' is not defined

Para acceder a subpartes de un vector, la misma sintaxis funciona como para listas: se extraen componentes (entradas) individuales con

In [ ]:
a = array([0, 1, 2, 3])
print(a[0], a[2])

y subvectores con

In [ ]:
b = a[1:3]
b

Nótese, sin embargo, que en este caso la variable `b` no es una copia de esta parte de `a`. Más bien, es una vista de `a`, así que ahora si hacemos:

In [ ]:
b[1] = 10
print(b)
print(a)

entonces la entrada correspondiente de a ¡también cambia! Este fenómeno también funciona con listas:

In [ ]:
l=[1,2,3]; k=l; k[1] = 10

In [ ]:
l

In [ ]:
k

En general, en *Python* las variables son nombres de objetos; al poner `b = a`, **tenemos ¡un mismo objeto con dos nombres!**

Por lo que si realmente queremos una copia de un arreglo, podemos usar la función `copy()` de `numpy`

In [ ]:
from numpy import copy
b = copy(a)
b

In [ ]:
b[1] = 10
print(b)
print(a)

In [ ]:
a = array([1,2,3,4],int)
b = array([2,4,6,8] ,int)

In [ ]:
2*a+1

In [ ]:
a*b

### *Ejercicio 1:* 
Suponga que los arreglos a y b se definen de la siguiente manera:

In [44]:
from numpy import array
a = array([1,2,3,4],int)
b = array([2,4,6,8] ,int)

In [47]:
b

array([2, 4, 6, 8])

In [45]:
a

array([1, 2, 3, 4])

¿Qué imprimirá la computadora al ejecutar las siguientes instrucciones? (Trata de averiguar la respuesta antes de intentarlo en la computadora).

a) `print(b/a+1)` 

b) `print(b/(a+1))` 

c) `print(1/a)` 

In [48]:
b/a+1

array([3., 3., 3., 3.])

In [49]:
b/(a+1)

array([1.        , 1.33333333, 1.5       , 1.6       ])

In [50]:
1/a

array([1.        , 0.5       , 0.33333333, 0.25      ])

### Arreglos numpy (Marices).

Las matrices se tratan como vectores de vectores, o listas de listas:

In [51]:
M = array( [ [1, 2], [3, 4] ] )
M

array([[1, 2],
       [3, 4]])

In [52]:
a = array([[1,2,3] ,[4,5,6]] ,float)
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


También se puede crear una matriz de ceros:

In [53]:
# from numpy import *
import numpy as np

In [54]:
Z=np.zeros([3,4] ,float)
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


y de unos:

In [55]:
U = np.ones([3,4] ,float)
print(U)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


La dimensión de la matriz se puede ver con

In [56]:
M

array([[1, 2],
       [3, 4]])

In [57]:
M.shape

(2, 2)

In [58]:
U.shape

(3, 4)

y se puede manipular con

In [59]:
M.shape = 4,1
print(M)

[[1]
 [2]
 [3]
 [4]]


o con

In [60]:
M.reshape( 2, 2 )

array([[1, 2],
       [3, 4]])

De hecho, eso es una manera util de crear las matrices:

In [61]:
M = r_[0:4].reshape(2,2)

NameError: name 'r_' is not defined

también podemos saber el tamaño con `size`

In [62]:
a = array([[1,2,3], [4,5,6]] ,int)

print(a.size)
print(a.shape)

6
(2, 3)


Tambien podemos crear una matriz desde una función:

In [70]:
def f(i, j):
    return i+j

In [66]:
f(2,2)

4

In [71]:
# Nos lo da como matriz por el np.
M = np.fromfunction(f, (3,3))
M

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [73]:
N = (1,(3,3))
N

(1, (3, 3))

Dado que las matrices son vectores de vectores, al hacer


In [74]:
print(M[0])

[0. 1. 2.]


nos regresa la primera componente de M, que es justamente un vector (el primer renglón de M). Si queremos cierta entrada de la matriz, entonces más bien necesitamos especificar dos coordenadas:


In [75]:
M[0][1]

1.0

In [76]:
M[0, 1]

1.0

In [77]:
M.item(1)

1.0

In [78]:
a = zeros([2,2] ,int)

a[0,1] = 1
a[1,0] = -1

print(a)

NameError: name 'zeros' is not defined

Para extraer ciertas renglones o columnas de `M`, utilizamos una extensión de la notación para vectores:

In [83]:
I = np.identity(10)
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [84]:
M[3:5]

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [85]:
M[:, 3:5]

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
M[3:9, 3:5]     #matriz identidad de 10x10

Una función poderosa para construir matrices repetidas es tile

In [ ]:
tile( M, (2,2) )

Otros métodos útiles son **`diagonal`**, que regresa una diagonal de un arreglo:

In [90]:
np.diagonal(I)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [94]:
np.diagonal(M, 1)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

y **`diag`**, que construye una matriz con el vector dado como diagonal:

In [92]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [93]:
np.diag([1,2,3], 2)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Por ejemplo, realicemos el siguiente producto matricial:

$
\begin{pmatrix}
1 & 3\\
2 & 4\\
\end{pmatrix}
\begin{pmatrix}
4 & -2\\
-3 & 1\\
\end{pmatrix}
+2
\begin{pmatrix}
1 & 2\\
2 & 1\\
\end{pmatrix}
=
\begin{pmatrix}
-3 & 5\\
0 & 2\\
\end{pmatrix}
$

In [154]:
A = np.array([[1,3],[2,4]])
A1 = np.array(A[0])
print(A1)
A2 = np.array(A[1])
print(A2)

[1 3]
[2 4]


In [131]:
B = np.array([[4,-2],[-3,1]])
B1 = np.array(B[0])
print(B1)
B2 = np.array(B[1])
print(B2)

[ 4 -2]
[-3  1]


In [150]:
M1 = np.array([[A1[0]*B1[0] + A1[1]*B2[0],A1[0]*B1[1] + A1[1]*B2[1]] , [A2[0]*B1[0] + A2[1]*B2[0],A2[0]*B1[1] + A2[1]*B2[1]]])
M1

array([[-5,  1],
       [-4,  0]])

In [110]:
C = np.identity(2) + np.array([[0,2],[2,0]])
C

array([[1., 2.],
       [2., 1.]])

In [152]:
FF = M1 + 2*C
print(FF)

[[-3.  5.]
 [ 0.  2.]]


In [ ]:
# a = A[0][0]*B[0][0] + A[0][1]*B[1][0]
# b = A[0][0]*B[0][1] + A[0][1]*B[1][1]
# c = A[1][0]*B[0][0] + A[1][1]*B[1][0]
# d = A[1][0]*B[0][1] + A[1][1]*B[1][1] 

In [168]:
D = np.zeros([2,2])
for i in range(2):
    for j in range(2):
        AA = A[i][j]
        BB = B[j][i]
        suma = AA+BB
        print("AA",AA,"j",j,"i",i)
        print("BB",BB,"j",j,"i",i)
        print(suma)

AA 1 j 0 i 0
BB 4 j 0 i 0
5
AA 3 j 1 i 0
BB -3 j 1 i 0
0
AA 2 j 0 i 1
BB -2 j 0 i 1
0
AA 4 j 1 i 1
BB 1 j 1 i 1
5


In [156]:
FF[0][0]

-3.0

In [114]:
F = np.dot(A,B) + 2*C
F

array([[-3.,  5.],
       [ 0.,  2.]])

In [ ]:
a = array([[1,3] ,[2,4]] ,int)
b = array([[4,-2] ,[-3,1]] ,int)
c = array([[1,2] ,[2,1]] ,int)

print(dot(a,b)+2*c)

In [ ]:
b = array(list(map(sqrt,a)),float)
b

#### Cargar arreglos desde un archivo de texto

Es posible tomar un conjunto de números guardados en un archivo de texto y convertirlos en un arreglo usando la biblioteca `loadtxt` de `numpy` de la siguiente manera:

In [172]:
from numpy import loadtxt

valores = loadtxt("valores.txt",float)
valores

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

**Nota:** Solo funciona para archivos que contengan una sola linea, con valores separados ya sea por una coma o un tabulador.

Así entonces podriamos calcular su promedio (*aritmetico*):

In [173]:
promedio = sum(valores)/len(valores)
print(promedio)

8.0


o el promedio de los cuadrados:

In [262]:
promedio2 = sum(valores**2)/len(valores)
print(promedio2)

NameError: name 'valores' is not defined

In [309]:
K = [i for i in range (1,5)]
print(K)
      
a1 = sum(K)
print(a1)
      
b1 = len(K)
print(b1)

c1 = a1/b1
print("Promedio aritmético:",c)

#K[0]
d = 1
for j in range (K[0],K[3]):
    d = K[j]*d

print(d)

e = d**(1/4)
print(e)

[1, 2, 3, 4]
10
4
Promedio aritmético: 5.5
24
2.213363839400643


In [326]:
N = 5
L = [i for i in range (1,N)]
logL = list(map(mt.log,L))
h = mt.exp(sum(logL)/len(logL))
h

2.2133638394006434

Pero también podemos calcular el promedio geometrico. Recordemos que el promedio geometrico de $n$ valores se define como:

### $ \displaystyle \overline{x} = \displaystyle \left[ \prod_{i = 1}^n x_i \right]^{\frac{1}{n}} $

Tomando el logaritmo natural a ambos lados, tenemos:

### $ \displaystyle \ln \overline{x} = \displaystyle \ln \left[ \prod_{i = 1}^n x_i \right]^{\frac{1}{n}} = \dfrac{1}{n} \sum_{i = 1}^n \ln x_i $

de tal manera que:

### $ \displaystyle \overline{x} = \displaystyle \exp \left( \dfrac{1}{n} \sum_{i = 1}^n \ln x_i \right)$

Asi entonces, para poder calcularlo podemos realizar lo siguiente:


In [324]:
from math import log,exp

valores = loadtxt("valores.txt",float)
logs = array(list(map(log,valores)),float)

geometrico = exp(sum(logs)/len(logs))
print(geometrico)

NameError: name 'loadtxt' is not defined

**Notese que** combinamos la función `map()` y la función `log()` para calcular los logaritmos, para posteriormente calcular la media aritmética de los valores resultantes.

Aunque quiza podemos ser más ingeniosos y hacerlo de la siguiente manera: 

In [ ]:
from numpy import log
from math import exp

valores = loadtxt("valores.txt",float)

geometrico = exp(sum(log(valores))/len(valores))
print(geometrico)

#### Obtener datos desde el usuario

Es posible obtener datos insertados por el usuario directamente en la *linea de comandos* donde se este interpretando `Python`, mediante el uso la función `input()` de la siguiente manera:

In [ ]:
x = input("Ingresa el valor de x: ")
print("El valor de x es" , x)

In [ ]:
temp = input("Ingresa el valor de la temperatura T: ")
T = float(temp)

print("El valor de T es" , T)

In [ ]:
y = float(input("Ingresa el valor de y: "))
print("El valor de y es",y)

### *Ejercicio 2:* 
Supongamos que se nos da la posición de un punto en un espacio bidimensional en coordenadas polares $r$,$\theta$ y queremos convertirlo a coordenadas cartesianas $x$, $y$. 

¿Cómo escribiríamos un programa para hacer esto?

### *Ejercicio 3:* 

Escribe un programa para realizar la operación inversa a la del ejemplo anterior. Es decir, pedir al usuario las coordenadas cartesianas $x$, $y$ de un punto en un espacio bidimensional, y calcular e imprimir las coordenadas polares correspondientes, con el ángulo $\theta$ dado en grados.